# Дисциплина «Искусственный интеллект»
## Рабочая тетрадь № 2 (Макаревич Сергей, БИСО-02-23)

### Библиотека NumPy
```
    NumPy (NumericalPython) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.
    Если у вас уже есть Python, вы можете установить NumPy с помощью командной строки:
    - pip install numpy
    Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:
    import numpy as np
    Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.
    Наиболее важные атрибуты объектов ndarray:
    ndarray.ndim - число измерений (чаще их называют "оси") массива.
    ndarray.shape - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
    ndarray.size - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
    ndarray.dtype - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том
числе и составные.
    ndarray.itemsize - размер каждого элемента массива в байтах.
    ndarray.data - буфер, содержащий фактические элементы массива.
    Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов. Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html
```

In [3]:
# Пример 1.2.1
# Задача: Создать массив 5x2, вывести все значения массива, значение элемента с индексом (3,1) и второй столбец.
import numpy as np
arr = np.random.rand(5, 2)
print(arr)
print('Элемент с индексом (3,1):', arr[3, 1])
print('Второй столбец:', arr[:, 1])

[[0.68182913 0.12886962]
 [0.62687007 0.5170907 ]
 [0.78188637 0.42398171]
 [0.87879998 0.12699038]
 [0.10014852 0.89128431]]
Элемент с индексом (3,1): 0.1269903821290661
Второй столбец: [0.12886962 0.5170907  0.42398171 0.12699038 0.89128431]


In [5]:
# Пример 1.2.2
# Задача: Создать векторы разного типа и вывести их значения.
v1 = np.zeros(10)
v2 = np.ones(10)
v3 = np.full(10, 5)
v4 = np.arange(10, 20)
print(v1, v2, v3, v4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5 5 5 5 5 5 5 5 5 5] [10 11 12 13 14 15 16 17 18 19]


In [7]:
# Пример 1.2.3
# Задача: Создать массив 10x10, найти минимум, максимум и среднее значение.
arr = np.random.rand(10, 10)
print(arr)
print('Минимум:', np.min(arr))
print('Максимум:', np.max(arr))
print('Среднее значение:', np.mean(arr))

[[0.9499151  0.29897177 0.28441678 0.28726459 0.33597211 0.05600582
  0.37229131 0.34764139 0.90440947 0.76544236]
 [0.39407085 0.89297061 0.37846869 0.26743682 0.64972558 0.08463107
  0.12990528 0.18946152 0.33182497 0.370838  ]
 [0.32930965 0.04057522 0.1503237  0.69671437 0.18781319 0.70843782
  0.45621356 0.85048716 0.72694192 0.35422174]
 [0.36893775 0.74951927 0.7349868  0.63462638 0.43386475 0.34015538
  0.39580149 0.29333954 0.95099853 0.59553931]
 [0.44965424 0.44631972 0.4074034  0.72168469 0.43373492 0.15051764
  0.65484042 0.55017371 0.72119792 0.98559958]
 [0.91266197 0.78043237 0.8716423  0.27358122 0.06394523 0.96460152
  0.75224382 0.08178921 0.70721925 0.00693228]
 [0.4281906  0.27428362 0.64753963 0.32408647 0.18698922 0.60012847
  0.95805866 0.28194974 0.9880615  0.2321471 ]
 [0.44655701 0.72398314 0.28724668 0.61662061 0.69836744 0.37771314
  0.62365991 0.64489026 0.38890488 0.59397671]
 [0.26796887 0.05281408 0.76094501 0.99255533 0.19712664 0.07962675
  0.87445331

In [9]:
# Пример 1.2.4
# Задача: Поменять местами две строки в матрице 5x5.
matrix = np.arange(25).reshape(5, 5)
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [11]:
# Пример 1.2.5
# Задача: Выяснить результат следующих выражений.
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [13]:
# Пример 1.2.6
# Задача: Отсортировать массив.
arr = np.random.rand(10)
print(np.sort(arr))

[0.04810851 0.06175251 0.41160985 0.47371198 0.47865035 0.50188246
 0.56248683 0.56731299 0.73818892 0.9887372 ]


In [15]:
# Задание 1.3.1
# Задача: Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# Задание 1.3.2
# Задача: Создать 5x5 матрицу со значениями от 0 до 4.
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [19]:
# Задание 1.3.3
# Задача: Создать массив 3x3x3 со случайными значениями.
arr = np.random.rand(3, 3, 3)
print(arr)

[[[9.69045316e-01 4.70182172e-01 6.41669393e-01]
  [7.18777011e-01 6.65695340e-02 3.50010463e-01]
  [9.96524430e-02 8.95804086e-01 1.34290451e-01]]

 [[9.58401091e-01 6.72016706e-02 6.64435461e-01]
  [7.92661001e-02 6.41131923e-04 8.26945603e-01]
  [6.76713213e-01 2.17861690e-01 6.66871860e-01]]

 [[4.98363129e-02 5.78957632e-01 6.82037842e-01]
  [8.97068164e-01 7.06767763e-01 7.01051489e-01]
  [2.81086765e-01 8.79805574e-01 8.84055693e-01]]]


In [21]:
# Задание 1.3.4
# Задача: Создать матрицу с 0 внутри и 1 на границах.
matrix = np.ones((5, 5))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
# Задание 1.3.5
# Задача: Создайте массив и отсортируйте его по убыванию.
arr = np.random.rand(10)
sorted_arr = np.sort(arr)[::-1]
print(sorted_arr)

[0.9472119  0.81006408 0.69104474 0.67845916 0.66532054 0.53182799
 0.49379752 0.39032154 0.20159965 0.00216076]


In [25]:
# Задание 1.3.6
# Задача: Создайте матрицу, выведите ее форму, размер и размерность.
matrix = np.random.rand(4, 4)
print('Матрица:', matrix)
print('Форма:', matrix.shape)
print('Размер:', matrix.size)
print('Размерность:', matrix.ndim)

Матрица: [[0.13615881 0.75866004 0.9368193  0.94619848]
 [0.52806383 0.58372699 0.28927927 0.58347545]
 [0.00581897 0.44618035 0.66093337 0.47720712]
 [0.98128041 0.75777658 0.34577006 0.10368936]]
Форма: (4, 4)
Размер: 16
Размерность: 2


### Библиотека Pandas
```
    Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких
источников.
    Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.
    Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:
   •  pip install pandas
    Для импорта библиотеки используйте команду:
    import pandas as pd
    Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.
    Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.
    DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.
```

In [88]:
# Пример 2.2.1
# Задача: Создать Series из списка Python, словаря Python, и массива Numpy.
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


In [90]:
# Пример 2.2.2
# Задача: Дано два Series, вывести первые элементы первого и все элементы после третьего из второго.
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


In [92]:
# Пример 2.2.3
# Задача: Создать новый DataFrame.
dataframe =pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

In [134]:
# Пример 2.2.4
# Задача: Загрузите фрейм данных по ссылке.

# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

HTTPError: HTTP Error 404: Not Found

In [126]:
# Пример 2.2.5
# Задача: Анализ фрейма данных (первые несколько строк, описательная статистика).
dataframe.head(2)

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian

In [128]:
dataframe.tail(3)

stream  slope elevation vegetation
4   False   flat      high    conifer
5    True  steep   highest    conifer
6    True  steep      high  chapparal

In [130]:
dataframe.shape

(7, 4)

In [132]:
# Пример 2.2.6
# Задача: Выберите срезы фрейма данных.
dataframe.iloc[1:4]

stream     slope elevation vegetation
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal

In [136]:
# Пример 2.2.7
# Задача: Отобрать строки на основе условия (пассажиры первого класса).
dataframe[dataframe['PClass'] == '1st'].head(2)

KeyError: 'PClass'

In [108]:
# Задание 2.3.1
# Задача: Найдите евклидово расстояние между двумя Series a и b.
import numpy as np
import pandas as pd

# Пример двух Series
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

# Вычисление евклидова расстояния
distance = np.sqrt(np.sum((a - b) ** 2))

print("Евклидово расстояние:", distance)

Евклидово расстояние: 5.196152422706632


In [104]:
# Задание 2.3.2
# Задача: Найдите ссылку на любой csv файл и создайте из него DataFrame.
url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
dataframe = pd.read_csv(url)
dataframe

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer
5    True     steep   highest    conifer
6    True     steep      high  chapparal

In [112]:
# Задание 2.3.3
# Задача: Проделайте с получившимся DataFrame действия из примеров 2.2.5-2.2.7.
dataframe.head(2)

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian

In [114]:
dataframe.tail(3)

stream  slope elevation vegetation
4   False   flat      high    conifer
5    True  steep   highest    conifer
6    True  steep      high  chapparal

In [116]:
dataframe.shape

(7, 4)

In [118]:
dataframe.describe()

stream  slope elevation vegetation
count       7      7         7          7
unique      2      3         4          3
top      True  steep      high  chapparal
freq        4      5         3          3

In [120]:
dataframe.iloc[1:4]

stream     slope elevation vegetation
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal

In [122]:
dataframe[dataframe['slope'] =='steep']

stream  slope elevation vegetation
0   False  steep      high  chapparal
2    True  steep    medium   riparian
3   False  steep    medium  chapparal
5    True  steep   highest    conifer
6    True  steep      high  chapparal

### Работа с числовыми данными
```
   Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж)
    Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1. 
   Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.
    На практике наиболее распространены следующие методы
нормализации признаков:
    • Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
    • Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.
   При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.
```

In [78]:
# Пример 3.2.1
# Задача: Прошкалируйте числовой признак в диапазон между двумя значениями.
import numpy as np
from sklearn import preprocessing

#Созать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Созать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

#Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

#Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [80]:
# Пример 3.2.2
# Задача: Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Созать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [82]:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


In [84]:
# Пример 3.2.3
# Задача: Масштабировать числовые столбцы DataFrame.
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest  = pd.DataFrame({
'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']
})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [86]:
# Задание 3.3.2
# Задача: Нормализовать два признака в DataFrame с использованием MinMax и Z-скейлинга.
import pandas as pd
from sklearn import preprocessing
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv' 
dataframe = pd.read_csv(url)
newdf=pd.DataFrame(data=dataframe, columns=['sepal_length_cm'])
scaler_minm = preprocessing.MinMaxScaler()
scaler_minm.fit(newdf)
scaled_features = scaler_minm.transform(newdf)
df_MinMax = pd.DataFrame(data = scaled_features)

stand_df=pd.DataFrame(data=dataframe, columns=['sepal_width_cm'])
scaler_stand = preprocessing.StandardScaler()
scaler_stand.fit(stand_df)
scaled_featur = scaler_stand.transform(stand_df)
df_Stand = pd.DataFrame(data = scaled_featur)

result = pd.concat([df_MinMax, df_Stand],axis=1,keys=["sepal_length_cm", "sepal_width_cm"])
result.head()

sepal_length_cm sepal_width_cm
                0              0
0        0.222222       1.032057
1        0.166667      -0.124958
2        0.111111       0.337848
3        0.083333       0.106445
4        0.194444       1.263460